-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "Normal"
}

game:GetService("ReplicatedStorage"):FindFirstChild("Remote Events").ActivateStarted:FireServer(unpack(args))
