local module = loadstring(game:HttpGet"https://raw.githubusercontent.com/LeoKholYt/roblox/main/lk_serverhop.lua")()
loadstring(game:HttpGet"https://raw.githubusercontent.com/VxleLUA/Dynamic-Offical/main/Modules/AutoFarmBeta/RemoveName.lua")()
wait(0.2)
loadstring(game:HttpGet"https://raw.githubusercontent.com/VxleLUA/Dynamic-Offical/main/Modules/AutoFarmBeta/EventStart.lua")()
wait(0.1)
loadstring(game:HttpGet"https://raw.githubusercontent.com/VxleLUA/Dynamic-Offical/main/Modules/AutoFarmBeta/StartKillTP.lua")()
wait(0.1)
loadstring(game:HttpGet"https://raw.githubusercontent.com/VxleLUA/Dynamic-Offical/main/Modules/AutoFarmBeta/StartKill.lua")()
wait(10)
module:Teleport(game.PlaceId)
